[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "bridge"
path = "src/lib.rs"

[dependencies]
deranged = "0.3.11"
rand = "0.9.0"
strum = { version = "0.26.3", features = ["derive"] }
